spring.application.name=notification-service
server.port=8083

# Kafka Consumer
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=notificationService
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=orderPlacedEvent:com.msb.ecom.notification_service.event.OrderPlacedEvent
spring.kafka.consumer.auto-offset-reset=earliest

# Mail (Mailpit / Mailtrap for dev)
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAILPIT_SMTP_PORT:1025}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
