apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: msb-ecom
data:
  # Database Hosts & Ports
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  MONGO_DB_NAME: "product-service"
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  POSTGRES_AUTH_HOST: "postgres-auth"
  POSTGRES_AUTH_PORT: "5432"
  AUTH_DB_NAME: "auth_service"
  AUTH_DB_USER: "auth"
  POSTGRES_KEYCLOAK_HOST: "postgres-keycloak"
  POSTGRES_KEYCLOAK_PORT: "5432"
  KEYCLOAK_DB_NAME: "keycloak"
  KEYCLOAK_DB_USER: "keycloak"

  # Messaging & Mail
  KAFKA_BOOTSTRAP_SERVERS: "broker:29092"
  MAIL_HOST: "mailpit"
  MAILPIT_SMTP_PORT: "1025"

  # Backend Service URLs for Gateway & Inter-service
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service:8082"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8083"
  PAYMENT_SERVICE_URL: "http://payment-service:8084"
  AUTH_SERVICE_URL: "http://auth-service:8085"
  KEYCLOAK_URL: "http://keycloak:8080"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: msb-ecom
type: Opaque
stringData:
  # Passwords
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  MYSQL_ROOT_PASSWORD: "mysql"
  AUTH_DB_PASSWORD: "password"
  KEYCLOAK_DB_PASSWORD: "password"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  JWT_SECRET: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
