spring.application.name=product-service
spring.data.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME:root}:${MONGO_INITDB_ROOT_PASSWORD:password}@localhost:${MONGO_PORT:27017}/${MONGO_INITDB_DATABASE:product-service}?authSource=admin
server.port=8080

# ─── Actuator ────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,liveness,readiness
management.endpoint.health.show-details=always
